"""
Django settings for TalkDoc project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1fe1boxg3gy(9!_8r)opkez=%@b1ojpf9!wp-0(5h2wo2qfuc4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = DEBUG


ADMINS = (
    ('mbilal', 'ans.bilal2000@gmail.com'),
)

MANAGERS = ADMINS

PROJECT_NAME = 'TalkDoc'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
	'NAME': 'TalkDoc',                       # Or path to database file if using sqlite3.
        'USER': 'root',                    # Not used with sqlite3.
        'PASSWORD': 'Xavor123',                   # Not used with sqlite3.
        'HOST': '',              # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '',                       # Set to empty string for default. Not used with sqlite3.

    }
}

ROOT = os.path.dirname(os.path.realpath(__file__))
MANAGE = '%s/manage.py' % ROOT

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_URL = '/login/'
INDEX_URL = '/talkdoc/home/'
ALTERNATE_INDEX_URL = '/talkdoc/reviews'

AUTH_PROFILE_MODULE = 'login.UserExtended'

MEDIA_ROOT = os.path.join(ROOT, 'media/')

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
# Examples: "http://media.lawrence.com/media/", "http://example.com/media/"
MEDIA_URL = '/media/'

# Absolute path to the directory static files should be collected to.
# Don't put anything in this directory yourself; store your static files
# in apps' "static/" subdirectories and in STATICFILES_DIRS.
# Example: "/home/media/media.lawrence.com/static/"
STATIC_ROOT = '%s/static' % ROOT

# URL prefix for static files.
# Example: "http://media.lawrence.com/static/"
STATIC_URL = '/media/static/'

STATICFILES_DIRS = (
    os.path.join(ROOT, 'media/'),
)

STATICFILES_DIRS = (
    os.path.join(ROOT, 'media/'),
)

PYSCRIPT_ROOT = '%s/py/' % STATIC_ROOT

MOON_ROOT = '%smoon/' % PYSCRIPT_ROOT

# URL prefix for admin static files -- CSS, JavaScript and images.
# Make sure to use a trailing slash.
# Examples: "http://foo.com/static/admin/", "/static/admin/".
ADMIN_MEDIA_PREFIX = '/adminmedia/'

DAJAXICE_MEDIA_PREFIX = 'dajaxice'

# Additional locations of static files
STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
)

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    #'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

# List of callables that know how to import templates from various sources.
TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
    'django.template.loaders.eggs.Loader',
)

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.contrib.auth.context_processors.auth',
    'django.core.context_processors.debug',
    'django.core.context_processors.i18n',
    'django.core.context_processors.media',
    'django.core.context_processors.static',
    'django.core.context_processors.request',
    'popup.context_processors.admin_media_prefix',
    'django.contrib.messages.context_processors.messages',
    'django.core.context_processors.tz',
    'social.apps.django_app.context_processors.backends',
    'social.apps.django_app.context_processors.login_redirect',
)

ROOT_URLCONF = 'urls'

TEMPLATE_DIRS = (
    '%s/templates/' % ROOT,
)


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dajaxice',
    'login',
    'TalkDoc',
# Social Auth App
    'social.apps.django_app.default'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(ROOT, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

FILE_UPLOAD_HANDLERS = (
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
)

# A sample logging configuration. The only tangible logging
# performed by this configuration is to send an email to
# the site admins on every HTTP 500 error.
# See http://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'mail_admins': {
#             'level': 'ERROR',
#             'class': 'django.utils.log.AdminEmailHandler'
#         }
#     },
#     'loggers': {
#         'django.request': {
#             'handlers': ['mail_admins'],
#             'level': 'ERROR',
#             'propagate': True,
#         },
#     }
# }

REDIRECT_FIELD_NAME = 'next'

# LDAP settings
AUTH_LDAP_SERVER_URI = ''
#AUTH_USER_MODEL
AUTH_USER_MODEL = "auth.User"
AUTH_LDAP_BIND_DN = ''
AUTH_LDAP_BIND_PASSWORD = ''

AUTH_LDAP_USER_SEARCH = LDAPSearch("", "")
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("", "")
AUTH_LDAP_GROUP_TYPE = GroupOfNamesType(name_attr="")

AUTH_LDAP_REQUIRE_GROUP = ""

AUTH_LDAP_USER_MAP = {"first_name":"givenName", "last_name":"sn", "email":"mail"}
AUTH_LDAP_PROFILE_ATTR_MAP = {"employee_number":"employeeNumber"}

AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "",
    "is_staff": "",
    "is_superuser": ""
}

AUTH_LDAP_ALWAYS_UPDATE_USER = True

AUTH_LDAP_FIND_GROUP_PERMS = True

AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 3600

# Adding LOGIN_REDIRECT_URL for Social Auth

LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_FACEBOOK_KEY = '740875159378915'
SOCIAL_AUTH_FACEBOOK_SECRET = '4515d161ff7688a2b46149bcee8588a8'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '659757065588-msck7u7dnrsvq54n4dnkrirbpng5mfmh.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'iCywQq3uSXXjg5HDILhnQ1vf'
SOCIAL_AUTH_TWITTER_KEY = 'UjVe3tDfhVREgzwHzLt6P2788'
SOCIAL_AUTH_TWITTER_SECRET = 'DmJw85UBOhmMVkckHQ7D56iyLEmZLK1I79CIZLuAML7xk0iwyw'

AUTHENTICATION_BACKENDS = (
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
#     Authentication_Backends for Social App
    'social.backends.facebook.FacebookOAuth2',
    'social.backends.google.GoogleOAuth2',
    'social.backends.twitter.TwitterOAuth',
)
EMAIL_HOST = None
HOST_EMAIL_ADDRESS = None

ORGANISER_EMAIL = "ans_bilal2000@live.com"
ORGANISER_PASS = "AnsiiStandard117"

APPROVAL_LINK = "http://127.0.0.1:8000/approval/"

